[package]
name = "algo-vanity-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algo_rust_sdk = "1.0"
clap = {version="4.3",features=["derive"]}
ctrlc = "3"
serde = "1.0"
serde_json = "1.0"